### ISSUE TITLE
[Bug] TLSV1_ALERT_PROTOCOL_VERSION(tls_record.cc:587))

### ISSUE THREAD

**Issue by JagandeepBrar** [CometTools/LunaSea#171]
**Describe the Bug**
https://www.reddit.com/r/LunaSeaApp/comments/fi01p9/tls_error/

**To Reproduce**
The user only has TLS v1.3 enabled, which is likely the cause in this situation.

**Expected Behaviour**
Valid and successful connection to the services.

**Comment by JagandeepBrar** [comment]
Resolving this bug has to be deferred, since TLS v1.3 is not properly supported in Dart itself, need to wait for `SecureSocket` to be updated to support it: https://github.com/dart-lang/sdk/issues/41061

**Comment by JigSawFr** [comment]
Hi 👋 
It seems to be solved on upstream 🙂

**Comment by JagandeepBrar** [comment]
This has finally been validated and confirmed to be working! I can't confirm with the currently public v5.1.0 but I can confirm that TLS v1.3 is fully working in the upcoming v6.0.0.
