### ISSUE TITLE
[Bug] Constant "pasting" notification with input fields in iOS 14

### ISSUE THREAD

**Issue by JagandeepBrar** [CometTools/LunaSea#222]
**Describe the Bug**
iOS 14 has introduced a new privacy feature which shows a notification for a user when the content from the pasteboard has been read by the application. This notification is constantly triggered on each widget rebuild (initial load, each new character entered).

**To Reproduce**
Run LunaSea on iOS 14.

**Expected Behaviour**
LunaSea at no point directly reads from the clipboard, so this notification should never appear unless a user explicitly pastes content from their clipboard in an input field.

**Versions**
Tested on: v3.0.0 (300003)

**Additional context**

As mentioned, LunaSea at no point directly reads from the clipboard itself, but this is a problem with the Flutter framework. This issue has been reported to the Flutter team, and will likely be fixed before iOS 14's release: https://github.com/flutter/flutter/issues/60145

**Comment by JagandeepBrar** [comment]
A temporary workaround to stop the annoying notification on actively refreshing pages (such as the clients, which refresh every couple of seconds) is to use the new copy text feature for text preview dialogs. Enter something like a show in Sonarr and copy the path, it will stop the notification from appearing anymore (until you copy text from outside of LunaSea again).

This is obviously non-ideal, still waiting on the Flutter team to update the framework.

**Comment by JagandeepBrar** [comment]
This appears to have been solved in a recent Flutter update, so I will be closing this issue for now. If it reoccurs, it will be reopened.

**Comment by ssbarnea** [comment]
This happens again with current versions and is extremele annoying. If I want to paste text copied from other apps, so be it, i do not need to approve it each time.
