### ISSUE TITLE
[Feature Request] App lock?

### ISSUE THREAD

**Issue by ohmantics** [CometTools/LunaSea#232]
This feels like the kind of app that wants to protect the credentials it’s been given by using FaceID/TouchID validation before the app uses the credentials, which should, of course be stored in the Keychain anyway.

**Comment by JagandeepBrar** [comment]
Adding authentication has definitely been considered, I have made a feedback board request for you that you can follow along/comment on: https://feedback.lunasea.app/70

I am going to close the issue though, as I try to keep the GitHub issues page for bugs and application issues.
