### ISSUE TITLE
[Feature Request] Custom Headers for Search

### ISSUE THREAD

**Issue by rg9400** [CometTools/LunaSea#234]
I really appreciate the custom headers being added for the modules. It allows me to keep the headers locked down via Organizr authentication or Authelia or some other security authentication while still allowing Lunasea to communicate.

However, I cannot do this for my search module (NZBHydra), which means I need to leave this service's endpoints open and exposed.

**Comment by JagandeepBrar** [comment]
Hey! This is definitely an oversight on my part, didn't factor in NZBHydra2 when I thought that headers wouldn't be useful for the search module. I have created a feedback board issue for you where you can follow along on progress, but it should be implemented in the near future: https://feedback.lunasea.app/73

I am going to close the issue however, as I try to keep GitHub issues to actual issues and bugs.
