### ISSUE TITLE
[Feature Request] Transmission Monitoring

### ISSUE THREAD

**Issue by dannyvfilms** [CometTools/LunaSea#244]
I don’t know if this is wandering into the territory of what is allowed based on the App Store guidelines, but this app is so clean I’d love it if I could check in on transfers in my Transmission client. Bonus points if we could add or delete them, but even just looking would be nice.

**Comment by JagandeepBrar** [comment]
Torrent support is being discussed on the feedback board here: https://feedback.lunasea.app/23

GitHub issues are reserved for actual bugs/issues, so I will be closing this issue. You can make any further comments in the feedback board.
