### ISSUE TITLE
[Feature Request] Trigger Manual Import

### ISSUE THREAD

**Issue by dannyvfilms** [CometTools/LunaSea#245]
This app nails almost all of the causal features I’d need for use on my phone, but the one notable one would be the ability to trigger a Manual Import in Radarr/Sonarr/Lidarr. Sometimes downloads don’t load in properly, and since the app makes it easy to start downloads without going to the computer, this would be a nice addition to round it out.

**Comment by JagandeepBrar** [comment]
As far as I can see, this is not a feature of any of their APIs sadly, so it cannot be implemented.

Also as mentioned in the other issue you made, GitHub issues are reserved for actual bugs/issues, so I will be closing this issue.
