### ISSUE TITLE
[Bug] Back button on Tautulli screens closes the app

### ISSUE THREAD

**Issue by lightglitch** [CometTools/LunaSea#252]
**Describe the Bug**
If you the Android back button when you are inside a Tautulli screen closes de app.

**Expected Behaviour**
Should go back or open the menu like the other modules.

**Versions**
Latest beta version

**Comment by lightglitch** [comment]
It also happens on settings module.

**Comment by JagandeepBrar** [comment]
Thanks for finding the issue, will begin investigating it shortly and have a fix in the next TestFlight/beta!

**Comment by JagandeepBrar** [comment]
This has been fixed in https://github.com/CometTools/LunaSea/commit/15eab71c09c67e32e54c211a7da5306834f5b830, and will be pushed out tonight in a new build!
