### ISSUE TITLE
[Feature Request] Deluge & Transmission Integration

### ISSUE THREAD

**Issue by Ashkaan** [CometTools/LunaSea#256]

**Comment by JagandeepBrar** [comment]
GitHub issues are reserved for actual issues, you can follow along on torrent support here: https://feedback.lunasea.app/23

**Comment by viggy96** [comment]
@JagandeepBrar That link appears to be broken, where should interested users follow the feature now?

**Comment by JagandeepBrar** [comment]
@viggy96 Apologies for that, here is the old link that is still accessible until the end of the month:

https://lunasea.nolt.io/23

Just recently switched to a new provider for the feedback board and am slowly copying over old feedback and their comments. Once a new post is available I will update you again.

**Comment by JagandeepBrar** [comment]
New feedback listing: https://feedback.lunasea.app/features/torrent-clients-support

**Comment by JohnGalt1717** [comment]
Also doesn't work.
