### ISSUE TITLE
[Bug] NZBGet cannot connect when using the given username and password field

### ISSUE THREAD

**Issue by Appeltaartu** [CometTools/LunaSea#261]
**Describe the Bug**
NZBGet cannnot connect when using the provided username and password field.

**To Reproduce**
Setup NZBGet and use the Username and Password field.

**Expected Behaviour**
Connected to NZBGet.

**Screenshots**
N.A

**Versions**
4.0.0 (4000102)

**Additional context**
There is a workaround by using the "Customer Headers" and then "Basic Authentication". You must leave the "Username" and "Password" field empty.

**Comment by JagandeepBrar** [comment]
This occurs when your username or password include special characters which cause the username and/or password to get parsed incorrectly and truncated at the wrong location.

Following the [NZBGet API](https://nzbget.net/api/), data is requested using the URL `http://<host>:<port>/<username>:<password>/jsonrpc`. If the username or password contain a `:` for example, or other reserved characters like `?`, `#`, or `$` for example, it will cause the username  or password to get incorrectly parsed.

I should add information in the prompts regarding this, as there is nothing I can do to fix this. Your workaround is exactly what you need to do to get around this, as that causes the authentication to get base64 encoded and attached as a header, so beyond the limitations mentioned in the basic authentication prompt (specifically a `:` in the username is not valid), you shouldn't have any issues with auth.

**Comment by Appeltaartu** [comment]
Thanks for your fast reply!

Isn't it good to check if those characters are used. When used give a message or something to let the user know. Other way that could work is recognize that those characters are in there and use the headers instead automatically.

**Comment by JagandeepBrar** [comment]
I could do that, but I decided to leave it to the end user as some users who uses customized networking configurations need more fine-grained control over the headers, especially one as generic as `authorization`. By giving the user the option, they can use the `authorization` header for security to the reverse proxy, then combine that with the username and password combination which they still have enabled on their local network for example. If I was to set the header, the same username and password credentials need to be used for both the reverse proxy and NZBGet, which isn't always the case.

**Comment by RichardKohlen** [comment]
Okay fair enough, I have a reverse proxy my self but without basic authentication. Thanks for your answer!

**Comment by Appeltaartu** [comment]
Okay fair enough, I have a reverse proxy my self but without basic authentication. Thanks for your answer!
