### ISSUE TITLE
[SABnzbd] scan API key QR code

### ISSUE THREAD

**Issue by sanderjo** [CometTools/LunaSea#268]
Feature suggestion:

Instead of typing / copy-pasting the SABnzbd API key, you could consider to have a feature in LunaSea to scan the QR code for the API key from SABnzb

![image](https://user-images.githubusercontent.com/1273502/99142131-84ac7300-2652-11eb-96bd-241ae587dbc3.png)

![image](https://user-images.githubusercontent.com/1273502/99142109-444cf500-2652-11eb-8e0f-0484b4ae1498.png)

It seems Flutter can scan QR codes:

https://pub.dev/packages/qrscan
https://medium.com/flutterdevs/scanning-generating-qr-code-in-flutter-3d5251a61244

**Comment by JagandeepBrar** [comment]
Hey there!

Thanks for doing the research and ensuring it's possible within Flutter! I definitely want to and plan to add this into LunaSea.

I will however be closing this issue in favour of a post I made on the feedback/request board. Here is the link so you can vote and/or comment on it further: https://feedback.lunasea.app/90
