### ISSUE TITLE
[Feature Request] Option to save filter option in Catalogue view

### ISSUE THREAD

**Issue by Pixxel123** [CometTools/LunaSea#271]
I'd really like the option to make the filter view save on app close. When I check my Catalogue view, I prefer to sort by Date Added, descending, however each time I open the app they display as Alphabetical and I have to manually change it.

A toggle in the settings for Save Current Filter on Exit would be handy!

Here's a screenshot of the option I mean:

![image](https://user-images.githubusercontent.com/36304206/99582632-4f997b00-29da-11eb-9f1f-5fb56a474928.png)

**Comment by JagandeepBrar** [comment]
This has actually been added to Sonarr in the latest TestFlight/Beta releases.

Settings -> Customization -> Sonarr -> Default Sorting

**Comment by rickytin** [comment]
Thanks for the Sonarr default setting, I change the setting to "Date Added" but it is from old to new TV shows and I would like the sort to be from new to old TV shows. 
Hope in the future you add this setting to Radarr.
