### ISSUE TITLE
[FEATURE REQUEST] Radarr Discover Movies

### ISSUE THREAD

**Issue by colethegamer123** [CometTools/LunaSea#272]
Hello Dear LunaSea Team,

Im a community member of Radarr and would like to ask about a feature request.

There is one nothing that none of the apps knows on IOS what is handling Radarr Servers.

**- Discover Movies -**

In the WebGUI there is a feature what is showing unseen movies what is not part of your library, here you can find movies what you doesnt know. You can add it them to your library with a button after choosing quality and location.

This feature would be really good for most of the users who wants to find new movies.

Here is a screenshot how it looks like in the gui:
![image](https://user-images.githubusercontent.com/62310407/100228204-9f1fff80-2f22-11eb-8fc2-d5a0eac8e0ed.png)

Platform: IOS

Thank you so much for your hard work and for the awesome application.
Best regards,

**Comment by JagandeepBrar** [comment]
Hey @colethegamer123 thanks for the feature request!

I have created a Feedback Board request for you here: https://feedback.lunasea.app/96

I will however be closing the GitHub issue, as I try to reserve it for actual issues/bugs with the application. You can vote on and comment on the feedback board and follow any progress there :)
