### ISSUE TITLE
[Bug] Long pressing back button in calendar resulting in black screen

### ISSUE THREAD

**Issue by julian-str** [CometTools/LunaSea#280]
**Describe the Bug**
I get a black screen when I long press the back button whenever I long press the back button in the calendar in the home area. I have to restart lunasea at this point.

**To Reproduce**
Choose an episode or movie in the calendar and long press back button. I have the calendar configured as standard view of the home area.

**Expected Behaviour**
Getting back to the calendar.

**Screenshots**
-

**Versions**
LunaSea TestFlight 40100007
iPad Pro 11 2020

**Comment by JagandeepBrar** [comment]
Thanks for identifying this, was immediately able to reproduce. Will put out a patch release to TestFlight and beta tomorrow to get this fixed.

**Comment by JagandeepBrar** [comment]
This bug has now been fixed and will be in the next TestFlight, likely today!

https://github.com/CometTools/LunaSea/commit/f98467951b7b8433774954a9780118a9fa84ca94
