### ISSUE TITLE
[Bug] <IOS Unable to fetch Sonnar releases>

### ISSUE THREAD

**Issue by bighops15** [CometTools/LunaSea#282]
**Describe the Bug**
As of today when I try to search for Sonnar releases I get an error message saying Unable to search Sonnar for releases.

**To Reproduce**
Trying to manually search for any releases in Sonnar.

**Expected Behaviour**
It should give me search results and it still works like normal in the Sonnar web GUI.

**Screenshots**
Screenshot of error log attached.

**Versions**
LunaSea on IOS version  @4.1.0
![Screenshot 2020-12-08 at 12 53 05 pm](https://user-images.githubusercontent.com/75677388/101486310-5cafe700-3954-11eb-8dfe-f3cfd3069d44.png)

**Additional context**

**Comment by JagandeepBrar** [comment]
Hi there, thanks for the bug report, this has already been detected and solved in the next release (which is currently pending review on the App Store)! You can join the TestFlight (link in the Settings of LunaSea) to get the update now.

**Comment by bighops15** [comment]
Thank you! Joined TestFlight version and all working now. Love this app by the way! 👍🏽

David
