### ISSUE TITLE
[Other] Add Siri / Shortcuts

### ISSUE THREAD

**Issue by EpicKris** [CometTools/LunaSea#294]
Siri / Shortcuts to:
- Pause queue [for x duration]
- Resume queue
- Set speed-limit to x%

**Comment by JagandeepBrar** [comment]
Hey there, thanks for the request.

We do use a feedback board for requests, and I have made a post for you that you can comment and vote on: https://feedback.lunasea.app/110

I am going to close this issue however, as to keep the GitHub issues dedicated to actual bugs and issues.
