### ISSUE TITLE
[Bug] <Sonnar unable to add new series or see list of Series>

### ISSUE THREAD

**Issue by bighops15** [CometTools/LunaSea#302]
**Describe the Bug**
When I go to the 'Series' tab it says 'an error has occurred. Also when I try to add a new show it says 'an error has occurred' 

[flog.txt](https://github.com/CometTools/LunaSea/files/5835384/flog.txt)
![IMG_6925640864CB-1]

(https://user-images.githubusercontent.com/75677388/105025025-ae17bf80-5a44-11eb-8cc1-099b517b2e5e.jpeg)

log files attached.

**To Reproduce**
Open Sonarr in LunaSea and navigate to the 'Series' tab or attempt to add a new show

**Expected Behaviour**
I expected to see my list of shows and be able to add new shows in the app.

**Screenshots**
Screenshots of logs with error messages attached

**Versions**
using latest TestFlight version - 4.2.1 (40201001)

**Additional context**
The problem persists whether I use the latest public version of the app or the TestFlight version.

**Comment by JagandeepBrar** [comment]
At any point, did fetching your list of series work?

It is receiving HTTP error 404 (not found), so you will need to check your host to ensure you are pointed to a valid instance of Sonarr.

**Comment by bighops15** [comment]
Hi there my Sonarr instance is definitely valid as I can view my upcoming shows, missing shows and history and search for new episodes from those sections. It’s just the Series section and when adding new shows where I get the error message. Any idea what I can do? Thanks!

**Comment by JagandeepBrar** [comment]
> my upcoming shows, missing shows and history and search for new episodes from those sections.

That is very strange and irregular. Could you possibly try updating/reinstalling Sonarr? Or would it be possible for you to send me your host and API key? I cannot replicate this on my side in anyway and no other users have reported a similar problem, but there must be something unique (and possibly broken) in your instance that is causing this issue. If those other calls are working, there is no reason that the series API call would be throwing a not found error.

If you are comfortable with sending me your details, can you send them to hello@lunasea.app?

**Comment by JagandeepBrar** [comment]
Closing this issue as we have solved the problem over email: When using Sonarr v2, ensure that you have not toggled the v3 features in the configuration.
