### ISSUE TITLE
[Other] Adding Info from Tautulli Playback to Items

### ISSUE THREAD

**Issue by xInsertx** [CometTools/LunaSea#305]
Under the Tautulli module, on item history details, can we get the playback info (container / video / audio) and transcode status.

I’ve been using the app heavily but still have to flick to another app or web UI for this info.

ie: 
![8E33A803-6D88-4410-A0E7-8CFEA52C631C](https://user-images.githubusercontent.com/10349764/105624290-cb99be80-5e74-11eb-9837-ad3234da28e5.jpeg)

**Comment by JagandeepBrar** [comment]
Thanks for the request! I have added the request to the LunaSea feedback board: https://feedback.lunasea.app/117

I will be closing the issue however, just to keep the issues around bugs/"system"-level requests.

I can say however, I do want to add this in and hopefully I can get it in within a release soon!
