### ISSUE TITLE
[Bug] Error when trying to search for something in -arrs

### ISSUE THREAD

**Issue by hbooo** [CometTools/LunaSea#308]
**Describe the Bug**
I have an error each time I try to search for a movie/tv show/music 

**To Reproduce**
Go to radarr, sonarr or lidarr in LunaSea and try to search for all missing or for a specific item

**Expected Behaviour**
Search should work without an error

**Screenshots**
![image](https://user-images.githubusercontent.com/242125/107577863-455ed580-6bf3-11eb-823b-b267b1aba10f.png)

**Versions**
LunaSea: 4.2.1 (40201001)
Sonarr: 3.0.4.1126-ls60 by linuxserver.io
Radarr: 3.0.2.4552-ls93 by linuxserver.io
Lidarr: 0.7.2.1878

**Additional context**
Log: 
![image](https://user-images.githubusercontent.com/242125/107578429-054c2280-6bf4-11eb-8719-5cb014d1cd81.png)

**Comment by JagandeepBrar** [comment]
Can you take a screenshot of the exception?

Also, does this happen for all -arrs or just Sonarr?

**Comment by hbooo** [comment]
![Screenshot_20210210-235507](https://user-images.githubusercontent.com/242125/107583692-94106d80-6bfb-11eb-8eb4-df42adda8115.png)
There you go

**Comment by JagandeepBrar** [comment]
Error 301 is an authentication error (unauthorized), how are you currently authenticating against the -arrs? Are you using an API key only, or are you using basic auth with a reverse proxy, etc.?

**Comment by hbooo** [comment]
I'm using a reverse proxy and an api Key :

http://mydns/**arr

I'm able to navigate to the arr module and see items but when i try an interactive search or all missing It doesn't work

**Comment by JagandeepBrar** [comment]
Is your reverse proxy possibly blocking requests that are not GET requests? Any "actions" will execute `POST`, `PUT`, or `DELETE` HTTP requests.

I personally, as well as many users, use a reverse proxy with the -arrs and have no issues with executing requests through it.

**Comment by hbooo** [comment]
Just recheck my configuration and try with https ://mydns/**arr instead of htpp://mydns/**arr

And now it works, sorry for that.
