### ISSUE TITLE
[Other] Magic keyboard trackpad support on iPad

### ISSUE THREAD

**Issue by psydrin** [CometTools/LunaSea#310]
I’d love to see two finger trackpad scrolling on pages along with swipe-back functionality. Not sure how difficult those are to implement but they’d be a great quality of life feature for the iPad app and those of us with keyboards.

**Comment by JagandeepBrar** [comment]
Hey there, you can follow along on keyboard support here: https://feedback.lunasea.app/b/User-Experience/p/keyboard-support

I have a pinned message regarding the current state of the request. 

I will be closing the issue however, to keep the GitHub issues for issues and bugs.
