### ISSUE TITLE
[Bug] Backup to Device does not work on iPad but works on iPhone

### ISSUE THREAD

**Issue by aniqueta** [CometTools/LunaSea#314]
**Describe the Bug**
Backup to Device does not work on iPad but works on iPhone

**To Reproduce**
1. Tap Backup to Device
2. Enter password
3. Tap backup

**Expected Behaviour**
Share sheet pops up on where to send backup config file

**Actual Behaviour**
No share sheet pop up on iPad (but share sheet pops up on iPhone)

**Versions**
4.2.1

**Additional context**
Also attempted after device restart. No other issues with share sheets in other apps.

**Comment by JagandeepBrar** [comment]
I am able to replicate this issue, thanks for reporting it. I am investigating, it might be an issue with the package being used for the sharesheet.

**Comment by JagandeepBrar** [comment]
Bug reported to the package: https://github.com/fluttercommunity/plus_plugins/issues/158

Need to wait for a response from them, as from tests this does appear to be a package issue.
