### ISSUE TITLE
[Bug] error adding new series 

### ISSUE THREAD

**Issue by uratrtl** [CometTools/LunaSea#320]
I’m able to connect under sonarr and browse my active lists but when I add a new show I get an error here is the log:

#0      _commandAddSeries (package:sonarr/src/commands/series/add_series.dart:49)
<asynchronous suspension>
#1      _State._onTap.<anonymous closure> (package:lunasea/modules/sonarr/modules/series_add_details/widgets/button_add_series.dart)
<asynchronous suspension>
 
 This is on both my iPad and iPhone.

**Comment by JagandeepBrar** [comment]
Do any actions work? Like can you toggle the monitor state of a series/season, edit a series, etc.?

**Comment by JagandeepBrar** [comment]
I am going to be closing this issue however, as this isn't a bug with LunaSea but a misconfiguration situation. Please read the README to contact me through one of the support channels (Reddit, Discord, etc.) where I can help debug the issue.
