### ISSUE TITLE
[Build] Can't build project

### ISSUE THREAD

**Issue by lightglitch** [CometTools/LunaSea#395]
Because you are using a local dependency:

https://github.com/CometTools/LunaSea/blob/master/pubspec.yaml#L45

I'm unable to build the project and test local developments.

**Comment by JagandeepBrar** [comment]
oops! Sorry about that, I'll get that fixed soon. Just need to publish a new version of the package first.

**Comment by JagandeepBrar** [comment]
This has been fixed with the latest PRs.

There were major changes to the codebase with these PRs, so if you have made changes to the codebase, it may be a difficult rebase as a warning.

**Comment by lightglitch** [comment]
Thx, looks like I also need to add my google services json for testing.
