### ISSUE TITLE
[Other] Docs

### ISSUE THREAD

**Issue by AliMickey** [CometTools/LunaSea#423]
If i went through and documented most of the features and put up a pr, would you consider merging after review? 
Or do you prefer to write out the documentation yourself?

**Comment by JagandeepBrar** [comment]
I would definitely look over them and merge them in! Feel free to add anything, but I do plan on actually fleshing it out myself before releasing v5.0.0 if you don't want to spend the time.

**Comment by AliMickey** [comment]
im happy to do everything on sonarr, radarr, tautulli as those are what i use.

**Comment by JagandeepBrar** [comment]
I am just going to close this issue for now, and we can discuss anything related to the documentation in the PR you have started.
