### ISSUE TITLE
[Other] <macOS Connection failed>

### ISSUE THREAD

**Issue by Pq11911** [CometTools/LunaSea#426]
i can't get Lunasea to connect to my sonarr server from macOS app but i can connect normally from iPhone! i tried deleting and reinstalling the app still doesn't connect. I tried backing up  my setting from iPhone and restoring it on macOS still not connecting.

`DioError [DioErrorType.other]: SocketException: Connection failed, address = XXXXX.usbx.me, port = 443
#0      DioMixin.assureDioError (package:dio/src/dio_mixin.dart:819)
#1      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678)
<asynchronous suspension>
#2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:586)
<asynchronous suspension>
`

**Comment by JagandeepBrar** [comment]
Can you access the host via URL in Safari/Chrome/etc.?

Also try opening Terminal and entering `ping XXXXX.usbx.me`. You can use Ctrl+C to cancel it after a few returned packets. Do you get a successful roundabout response, is the packet loss not 0%?

**Comment by JagandeepBrar** [comment]
Hey @Pq11911, I will be closing this issue as it is a support request, and instead if you need any further help you can reach out in one of the methods in the next message.
