### ISSUE TITLE
Cannot connect to Radarr

### ISSUE THREAD

**Issue by wesh30** [CometTools/LunaSea#472]
All other modules are working. Radarr was working and now for some reason I can no longer connect. I can access it through a browser but LunaSea returns the following error. I have double checked the url since it's giving a 404 in the message.

DioError [DioErrorType.response]: Http status error [404]
#0      DioMixin.assureDioError (package:dio/src/dio_mixin.dart:819)
#1      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678)
<asynchronous suspension>
#2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:586)
<asynchronous suspension>

**Comment by JagandeepBrar** [comment]
Hey @wesh30,

With the release of v5.0.0 of LunaSea, we now use the v3 API path. This was naturally introduced with Radarr v3.0.0 (and higher), which was initially released back in November 2020.

You'll need to upgrade your instance of Radarr to the latest version to continue using LunaSea. The upgrade path should be relatively painless, and typically just involves installing Radarr v3 over your current instance!

**Comment by wesh30** [comment]
It's a little more complicated for me since I was using a docker image under unRAID but I'm sure I can find a v3 image. Thank you.
