### ISSUE TITLE
[Bug] Unable to download torrent/magnet from Index search

### ISSUE THREAD

**Issue by Generator** [CometTools/LunaSea#483]
**Describe the Bug**
From indexer search when 'clicked' on download does nothing.  
I've Jackett and Prowlarr setup on different search indexer. Both are working properly (Jackett blackhole, Prowlarr download client)

**To Reproduce**
1. Install and setup Jackett or Prowlarr
2. Add indexer to LunaSea
3. Search and Download

**Expected Behaviour**
When clicked on download send torrent/magnet to Blackhole or Torrent Client

**Versions**
LunaSea: 5.1.1
Jackett: v0.18.545
Prowlarr: 0.1.0.768
OS: Debian (Buster)

**Comment by JagandeepBrar** [comment]
This is currently not a feature of LunaSea. You cannot send to other clients that aren't supported in LunaSea, as it downloads and forwards it to the client. 

Because of this, only SABnzbd and NZBGet are supported.
