### ISSUE TITLE
[Bug] Lidarr: Failed to Fetch Artists

### ISSUE THREAD

**Issue by StormPooper** [CometTools/LunaSea#488]
**Describe the Bug**
When I attempt to access the Artists tab in Lidarr, I get an error and a retry prompt. Looking at the logs, I get the following:

<table>
<tr>
	<td>Error
	<td>Lidarr: Failed to fetch artists
<tr>
	<td>Class
	<td>package:lunasea/modules/lidarr/core/api/api.dart
<tr>
	<td>Method
	<td>LidarrAPI.getAllArtists
<tr>
	<td>Exception
	<td>NoSuchMethodError: The getter 'name' was called on null.<br/>Receiver: null<br/>Tried calling: name
</table>

**To Reproduce**
Not 100% sure, happened consistently since I installed it, but only just found the log section in Settings. Looking at the code mentioned, I suspect it is failing to get quality or metadata (which is odd as you're checking if it is null before checking accessing `name` on it), but as far as I can tell they should all be set. My only potential theory is I have the "Various Artists" special artist in my list with metadata set to None, but I've tried changing it to Everything to no avail. Every artist has been set to the same quality profile (manually confirmed this by setting it again in the Mass Editor).

**Expected Behaviour**
A list of my artists.

**Versions**
LunaSea: 5.1.0 (50100004) Android (Google Play)
Lidarr: 0.8.1.2135

**Additional context**
Radarr and Sonarr working with no issues with similar configuration (LinuxServer.io Docker containers). I'm able to add artists and the Missing/History tabs work with no issues.

**Comment by JagandeepBrar** [comment]
Thank you for the detailed breakdown, I will definitely investigate this for the next release!

**Comment by StormPooper** [comment]
No problem, let me know if you want me to test any builds against my library.

**Comment by StormPooper** [comment]
As part of a library cleanup, I changed a few artists to have a metadata profile of None and deleted a couple of artists. It's now working perfectly in LunaSea, so unfortunately I won't be able to test any changes.

My guess is somehow one of the artists had literally no profile rather than the None profile, but I doubt I can get it back into that scenario as it was probably from a much older build, since most of the artists I changed had been in my library from the start.

**Comment by JagandeepBrar** [comment]
@pr0xyfl00d3r Sorry for the late response, but you are experiencing a different error which is related to incorrectly setting the host for Lidarr and it is unable to parse the response correctly.

**Comment by pr0xyfl00d3r** [comment]
hi, what sort of setting is wrong? it does list all artist but does not go into an artist?

**Comment by pr0xyfl00d3r** [comment]
Hi, please can you help, i have got the setting like Sonarr and radarr but they work ok

**Comment by JagandeepBrar** [comment]
@pr0xyfl00d3r Reach out via one of the support channels (Reddit, Discord, Email) and I can try to help solve the problem!

**Comment by pr0xyfl00d3r** [comment]
Ok will do

**Comment by JagandeepBrar** [comment]
@pr0xyfl00d3r Just a heads up, I believe I have found the root cause of this problem and have fixed it for the next release!

Just to confirm my assumptions, are you running the nightly versions of Lidarr?

**Comment by pr0xyfl00d3r** [comment]
Yes I am
