### ISSUE TITLE
[Bug] Flutter index issue

### ISSUE THREAD

**Issue by J-Lich** [CometTools/LunaSea#489]
**Describe the Bug**
Ever time I add content (new show/movie) in sonarr Radarr I get the following error (and no content added): 

`type` '_GrowableList<dynamic>' is not a subtype of type 'Map<String, dynamic>'

**To Reproduce**
Click “Add Movie” or “Add Show” (Radarr or Sonarr respectively)

**Expected Behaviour**
Content added to service

**Screenshots**
screenshot is just the error log above. Feel free to contact me for more.

**Additional context**
Ia m running a reverse proxy, although I have not been able to determine if this is related.

**Comment by JagandeepBrar** [comment]
Hey there,

This isn't actually an issue with LunaSea, but with the host you have configured. It is redirecting, and a POST request does not forward the body on a redirect which is the causation of this error. It's why you're only getting this error when trying to "create" content, which is what POST requests are for.

Ensure that:
- You have set the correct default protocol (http or https)
- If you have a URL base, that you appended it to the host
- That your reverse proxy isn't doing any 3xx redirects
