### ISSUE TITLE
[Bug] Calendar/Schedules

### ISSUE THREAD

**Issue by Darkham42** [CometTools/LunaSea#493]
**Describe the Bug**
In Settings > Configuration > Dashboard > Calendar Settings > Starting Type
Calendar icon is for schedule, and schedule icon for calendar, and 
Seems a little weird, and more than a picto invert params there is a problem, if we don't relaunch the app choice seems not kept

**To Reproduce**
Go to Settings > Configuration > Dashboard > Calendar Settings > Starting Type change for the other one not already choose, go back to dashboard (in my case dashboard default page is calendar) the calendar/schedule don't change for your choice until restarting the app.

**Expected Behaviour**
Calendar picto for calendar choice and schedule picto for schedule choice.
Don't have to restart the app.

**Screenshots**
![Screenshot_20211017-032947](https://user-images.githubusercontent.com/6454197/137606912-e8e46c10-460d-4941-85b8-3ab36a866185.png)

**Versions**
LunaSea: 5.1.1 Android (Google Play, Beta user)

**Comment by JagandeepBrar** [comment]
Fixed in https://github.com/CometTools/LunaSea/commit/5319c631b7e4898f2856347f052b369abcead12d
