### ISSUE TITLE
Broken Sonarr connection after iOS update

### ISSUE THREAD

**Issue by H3KT1C** [CometTools/LunaSea#550]
After the major update on ios, Sonarr can no longer connect, when I test the connection this is the log below from the error on get.

Radarr and SABnzbd still work flawlessly

DioError [DioErrorType.response]: Http status error [401]
Source stack:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:473)
#1      DioMixin.request (package:dio/src/dio_mixin.dart:468)
#2      DioMixin.get (package:dio/src/dio_mixin.dart:55)
#3      _commandGetStatus (package:sonarr/src/controllers/system/get_status.dart:4)
#4      SonarrController_System.getStatus (package:sonarr/src/controllers/system.dart:15)
#5      _State._testConnection.<anonymous closure> (package:lunasea/modules/settings/routes/configuration_sonarr/pages/connection_details.dart:139)
#6      _State._testConnection.<anonymous closure> (package:lunasea/modules/settings/routes/configuration_sonarr/pages/connection_details.dart:117)
#7      new LunaButton._.<anonymous closure> (package:lunasea/core/ui/button.dart:39)
#8      new LunaButton._.<anonymous closure> (package:lunasea/core/ui/button.dart:36)
#9      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989)
#10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198)
#11     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608)
#12     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296)
#13     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267)
#14     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157)
#15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:443)
#16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419)
#17     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322)
#18     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374)
#19     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338)
#20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296)
#21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279)
#22     _rootRunUnary (dart:async/zone.dart:1442)
#23     _CustomZone.runUnary (dart:async/zone.dart:1335)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244)
#25     _invoke1 (dart:ui/hooks.dart:170)
#26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331)
#27     _dispatchPointerDataPacket (dart:ui/hooks.dart:94)

**Comment by JagandeepBrar** [comment]
A 401 is an authentication error, can you check and make sure that your host/API key information are still correct?

Either way, this is not a problem with LunaSea + Sonarr but something with your config, we can continue the conversation here (or on a support channel) but will be closing the issue for now.
