### ISSUE TITLE
[Bug] Weblate reporting errors, cannot merge

### ISSUE THREAD

**Issue by diemade** [CometTools/LunaSea#575]
**To Reproduce**
Go to https://hosted.weblate.org/projects/lunasea/
try to translate anything

**Expected Behaviour**
Pull request

**Observed Behaviour**
Translation ist locked. There ist this message:

Rebasing (1/1)
error: could not apply f4bdfc51... fix(workflows): Improve quality of alpha build workflows (#574)
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply f4bdfc51... fix(workflows): Improve quality of alpha build workflows (#574)
Auto-merging .github/workflows/build_alpha_macos.yml
CONFLICT (content): Merge conflict in .github/workflows/build_alpha_macos.yml
Auto-merging .github/workflows/build_alpha_ios.yml
CONFLICT (content): Merge conflict in .github/workflows/build_alpha_ios.yml
Auto-merging .github/workflows/build_alpha_android.yml
CONFLICT (content): Merge conflict in .github/workflows/build_alpha_android.yml
 (1)

**Comment by JagandeepBrar** [comment]
Error should be fixed now, sorry about that!
